# Generated by Django 3.0.4 on 2020-03-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_remove_project_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('Office', 'Office'), ('Residential', 'Residential'), ('Commercial', 'Commercial')], max_length=200, null=True),
        ),
    ]
